# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1a66e9d9e9d63c95c5f302a0d546c77580dffb036817af038e842f04daa2bcbf680ea7967b1cc64e3a77b5a7103066885a3fa9eeb3590229294248f82d848bf

test:
  secret_key_base: 9e772e203d9a8841830df406ea78c2430f1d63b7c2def723d1a9d834f064e6e070258f8ae5d3d9e0654f2b69eea8a321746307b83b0d05697603b638f1bb2c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
